version: '2'

services:
  db_needtofix:
    container_name: postgres_needtofix
    image: postgres:alpine
    networks:
      - internal
    labels:
      - traefik.enable=false
    restart: always

  web_needtofix:
    container_name: web_needtofix
    build: ./need2fix
    command: sh /code/run.sh
    volumes:
      - ./need2fix:/code
      - /var/www/need/static/
      - /var/www/need/media/
    networks:
      - internal
    labels:
      - traefik.enable=false
    depends_on:
      - db_needtofix

  nginx_needtofix:
      container_name: nginx_needtofix
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/:/etc/nginx/conf.d/
      volumes_from:
        - web_needtofix
      networks:
        - internal
        - proxy
      labels:
        - traefik.enable=true
        - traefik.backend=nginx_needtofix
        - traefik.frontend.passHostHeader=true
        - "traefik.frontend.rule=Host:service.sci.tu.ac.th;PathPrefixStrip:/need2fix"
        - traefik.docker.network:proxy
        - traefik.port=80
      depends_on:
        - web_needtofix

networks:
  proxy:
    external: true
  internal:
    external: false