version: '2'

services:
  db_needtofix:
    container_name: postgres_needtofix
    image: postgres:alpine
    networks:
      - internal
    restart: always

  web_needtofix:
    container_name: web_needtofix
    build: ./need2fix
    command: sh /code/run.sh
    volumes:
      - ./need2fix:/code
      - /var/www/need/static/
      - /var/www/need/media/
    networks:
      - internal
    depends_on:
      - db_needtofix

  nginx_needtofix:
      container_name: nginx_needtofix
      image: nginx:alpine
      ports:
        - "80:80"
      volumes:
        - ./nginx/:/etc/nginx/conf.d/
      volumes_from:
        - web_needtofix
      networks:
        - internal
        - proxy
      depends_on:
        - web_needtofix

networks:
  proxy:
    external: true
  internal:
    external: false